/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          50: '#f6f6f6',
          100: '#ebebeb',
          200: '#d5d5d5',
          300: '#b0b0b0',
          400: '#8a8a8a',
          500: '#656565',
          600: '#525252',
          700: '#404040',
          800: '#2e2e2e',
          900: '#1c1c1c',
          950: '#0a0a0a',
        },
        'navy-deep': {
          50: '#e6e8ff',
          100: '#d3d6ff',
          200: '#b5baff',
          300: '#8c94ff',
          400: '#646eff',
          500: '#484cff',
          600: '#3a39ff',
          700: '#3029e6',
          800: '#2821b8',
          900: '#221d8a',
          950: '#111220',
        },
        'warm-red': {
          50: '#fff1f1',
          100: '#ffe1e1',
          200: '#ffc5c5',
          300: '#ff9d9d',
          400: '#ff6b6b',
          500: '#F05454',
          600: '#D64545',
          700: '#b32d2d',
          800: '#8a2222',
          900: '#6d1b1b',
          950: '#450f0f',
        },
        'cool-blue': {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3B82F6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        'premium-dark': {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#0b1220',
        },
        'premium-card': {
          DEFAULT: '#1A2238',
        },
        'premium-text': {
          primary: '#E5E7EB',
          secondary: '#9CA3AF',
        },
        amber: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        green: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22C55E',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        red: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        gold: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Custom dark theme colors
        'dark-main': 'hsl(var(--dark-main))',
        'dark-nav': 'hsl(var(--dark-nav))',
        'dark-card': 'hsl(var(--dark-card))',
        'dark-input': 'hsl(var(--dark-input))',
        'dark-border': 'hsl(var(--dark-border))',
        'dark-text': 'hsl(var(--dark-text))',
        'dark-text-light': 'hsl(var(--dark-text-light))',
        'dark-gold': 'hsl(var(--dark-gold))',
      },
      backgroundColor: {
        'dark-main': '#1c1c1c',
        'dark-sidebar': '#2e2e2e',
        'dark-card': '#404040',
        'dark-input': '#525252',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        popover: 'hsl(var(--popover))',
        primary: 'hsl(var(--primary))',
        secondary: 'hsl(var(--secondary))',
        muted: 'hsl(var(--muted))',
        accent: 'hsl(var(--accent))',
        destructive: 'hsl(var(--destructive))',
      },
      textColor: {
        'dark-text': '#f6f6f6',
        'dark-muted': '#8a8a8a',
        'gold-text': '#fbbf24',
        'red-text': '#ef4444',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive-foreground))',
      },
      borderColor: {
        DEFAULT: 'hsl(var(--border))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      }
    },
  },
  plugins: [require('tailwindcss-animate')],
}